import { draftMode } from 'next/headers';
import { redirect } from 'next/navigation';
import { NextRequest, NextResponse } from 'next/server';

/**
 * Mark route as dynamic (not statically generated)
 * This route performs server-side validation and uses redirect()
 */
export const dynamic = 'force-dynamic';

/**
 * Preview API Route
 *
 * Handles preview mode for draft/scheduled content with token-based validation.
 *
 * Uses the HWP Previews approach with:
 * - Cryptographic token validation via WordPress transients
 * - Flexible URL parameter resolution
 * - FLATWP_SECRET for secure secret validation
 *
 * Flow:
 * 1. WordPress editor clicks "Preview in Next.js" button
 * 2. WordPress generates preview URL with token, secret, and dynamic parameters
 * 3. This route validates the secret matches FLATWP_SECRET
 * 4. This route validates the token with WordPress
 * 5. If valid, enables draft mode and redirects to post URL
 * 6. Post page detects draft mode and fetches draft content
 *
 * Query Parameters:
 * - secret: Must match FLATWP_SECRET environment variable
 * - token: Unique preview token generated by WordPress (validated via REST API)
 * - id: Post ID (used for validation)
 * - slug: Post slug (used for redirect path)
 * - type: Post type - determines redirect path (default: 'post')
 *
 * Additional parameters are passed through but not required
 * (e.g., year, month, day, category, author, etc.)
 */
export async function GET(request: NextRequest) {
  // Get URL parameters
  const searchParams = request.nextUrl.searchParams;
  const secret = searchParams.get('secret');
  const token = searchParams.get('token');
  const id = searchParams.get('id');
  const slug = searchParams.get('slug');
  const postType = searchParams.get('type') || 'post';

  // Validate required parameters
  if (!secret || !token || !id) {
    console.error('Preview: Missing required parameters', {
      hasSecret: !!secret,
      hasToken: !!token,
      hasId: !!id,
    });
    return NextResponse.json(
      { error: 'Missing required parameters: secret, token, id' },
      { status: 400 }
    );
  }

  // Verify secret matches environment variable
  if (secret !== process.env.FLATWP_SECRET) {
    console.error('Preview: Invalid secret provided');
    return NextResponse.json(
      { error: 'Invalid secret' },
      { status: 401 }
    );
  }

  // Validate token with WordPress
  try {
    const wordpressUrl = process.env.NEXT_PUBLIC_WORDPRESS_API_URL?.replace(
      '/graphql',
      ''
    );

    if (!wordpressUrl) {
      console.error('Preview: WordPress URL not configured');
      return NextResponse.json(
        { error: 'WordPress URL not configured' },
        { status: 500 }
      );
    }

    // Validate token via WordPress REST API
    const validateResponse = await fetch(
      `${wordpressUrl}/wp-json/flatwp/v1/preview/validate`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ token }),
      }
    );

    if (!validateResponse.ok) {
      console.error('Preview: Token validation failed', {
        status: validateResponse.status,
      });
      return NextResponse.json(
        { error: 'Invalid or expired preview token' },
        { status: 401 }
      );
    }

    const validationData = await validateResponse.json();

    // Verify post ID matches
    const postId = parseInt(id, 10);
    if (validationData.post_id !== postId) {
      console.error('Preview: Post ID mismatch', {
        expected: postId,
        actual: validationData.post_id,
      });
      return NextResponse.json(
        { error: 'Post ID mismatch' },
        { status: 400 }
      );
    }

    // Determine post slug for redirect
    // Use slug from URL parameters, fallback to empty if not provided
    const redirectSlug = slug || '';

    if (!redirectSlug) {
      console.error('Preview: Post slug not provided');
      return NextResponse.json(
        { error: 'Post slug not provided' },
        { status: 400 }
      );
    }

    // Enable draft mode
    (await draftMode()).enable();

    // Determine redirect path based on post type
    // Supports flexible routing patterns
    let redirectPath: string;
    switch (postType) {
      case 'page':
        redirectPath = `/${redirectSlug}`;
        break;
      case 'post':
        redirectPath = `/blog/${redirectSlug}`;
        break;
      default:
        // For custom post types, use pattern: /{post_type}/{slug}
        redirectPath = `/${postType}/${redirectSlug}`;
        break;
    }

    console.log('Preview: Token validated, enabling draft mode', {
      postId,
      postType,
      redirectPath,
    });

    // Redirect to the post with draft mode enabled
    redirect(redirectPath);
  } catch (error) {
    console.error('Preview: Validation error', error);
    return NextResponse.json(
      { error: 'Failed to validate preview token' },
      { status: 500 }
    );
  }
}
