/**
 * Search Index Types
 * Types for the search index generated by WordPress FlatWP plugin
 */

import type { FuseResultMatch } from 'fuse.js';

export interface SearchIndexItem {
  /** Post ID */
  id: number;
  /** Post title */
  title: string;
  /** Post excerpt (max 100 chars) */
  excerpt: string;
  /** Post slug */
  slug: string;
  /** Post URL path */
  url: string;
  /** Post type (post, page, etc.) */
  type: string;
  /** Category names */
  categories: string[];
  /** Tag names */
  tags: string[];
  /** Published date (ISO string) */
  date: string;
  /** Author name */
  author?: string;
}

export interface SearchIndex {
  /** Array of searchable posts */
  posts: SearchIndexItem[];
  /** Index version/hash for cache busting */
  version: string;
  /** Generation timestamp */
  generated: string;
  /** Total posts in index */
  total: number;
}

export interface SearchResult extends SearchIndexItem {
  /** Fuse.js match score (lower is better) */
  score?: number;
  /** Matched indices for highlighting */
  matches?: readonly FuseResultMatch[];
}

export interface SearchOptions {
  /** Maximum number of results to return */
  limit?: number;
  /** Minimum score threshold (0-1, lower is better) */
  threshold?: number;
  /** Fields to search in */
  keys?: string[];
}
